const weekly={S36:{planned:1242,present:1102,absent:140,assembly:32570.27,disassembly:13000.47,productivity:41.4},S37:{planned:1242,present:1105,absent:137,assembly:32095.05,disassembly:12822.72,productivity:40.6},S38:{planned:1242,present:1098,absent:144,assembly:33932.42,disassembly:13105.13,productivity:42.8},S39:{planned:1242,present:1091,absent:151,assembly:33862.11,disassembly:13243.91,productivity:43.2}};
const all={planned:14952,present:13340,absent:1612,assembly:325767,disassembly:130809,productivity:41.1};
const activities=[
 {id:'1.2',activity:'Montagem de Andaime na Torre da CWA-297',local:'CWA-297',leader:'Geciclei / Ernande',shift:'Diurno',status:'Em andamento'},
 {id:'2.4',activity:"Montagem eletromecânica das TR's - Continental",local:'TRs 09 @ 20',leader:'Marivaldo Meireles',shift:'Diurno',status:'Em andamento'},
 {id:'3.1',activity:'Montagem de suportes e leitos',local:'ED-2036KS-01',leader:'Rogerio / Giles / Nerivan',shift:'Diurno',status:'Em andamento'},
 {id:'4.1',activity:'Montagem de Andaime - Parada Usina B',local:'TR-2032KS-32',leader:'Cleber Sacramento',shift:'Diurno',status:'Concluído'},
 {id:'2.7',activity:'Apoio na montagem do Chapéu Chinês',local:'TR-2012KS-11',leader:'Cleber Sacramento',shift:'Diurno',status:'Programado'},
 {id:'1.14',activity:'Montagem de Andaime para montagem das colunas',local:'CWP 005 • EL. 294/295',leader:'Adilton de Jesus',shift:'Noturno',status:'Em andamento'}
];
const fmt=n=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(n);
const $=(q,p=document)=>p.querySelector(q);const $$=(q,p=document)=>[...p.querySelectorAll(q)];
function navigate(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#sidebar').classList.remove('open');scrollTo({top:0,behavior:'smooth'});if(id==='producao')renderProductivity();}
$$('.nav-link').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));$('#menuToggle').onclick=()=>$('#sidebar').classList.toggle('open');
function renderKpis(key='all'){const d=key==='all'?all:weekly[key];const absent=d.absent/d.planned*100;const total=d.assembly+d.disassembly;const cards=[['PRODUÇÃO TOTAL',fmt(total),'metros lineares','--cyan'],['PRODUTIVIDADE',fmt(d.productivity),'ML/MOD/dia • Meta 42','--teal'],['EFETIVO PLANEJADO',fmt(d.planned),'apontamentos acumulados','--blue'],['PRESENTES',fmt(d.present),'apontamentos acumulados','--cyan'],['ABSENTEÍSMO',fmt(absent)+'%','referência 10% a 13%','--orange'],['DESMONTAGEM',fmt(d.disassembly/total*100)+'%','participação na produção','--purple']];$('#kpiGrid').innerHTML=cards.map((c,i)=>`<div class="kpi ${i===0?'featured':''}" style="--accent:var(${c[3]})"><span>${c[0]}</span><strong>${c[1]}</strong><small class="${i===1&&d.productivity>=42?'good':''}">${c[2]}</small></div>`).join('');$('#gaugeValue').textContent=fmt(d.productivity/42*100)+'%';$('#gauge').style.setProperty('--value',Math.min(100,d.productivity/42*100)+'%')}
function bars(el,series,keys,colors){const w=700,h=205,p={l:42,r:10,t:12,b:30};const max=Math.max(...series.flatMap(x=>keys.map(k=>x[k])))*1.15;let svg=`<svg viewBox="0 0 ${w} ${h}" role="img">`;for(let i=0;i<5;i++){let y=p.t+(h-p.t-p.b)*i/4;svg+=`<line class="grid-line" x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}"/><text class="axis-label" x="2" y="${y+3}">${fmt(max*(1-i/4))}</text>`}const gw=(w-p.l-p.r)/series.length;const bw=Math.min(14,(gw-18)/keys.length);series.forEach((d,i)=>{keys.forEach((k,j)=>{let bh=(h-p.t-p.b)*d[k]/max;let x=p.l+i*gw+gw/2+(j-(keys.length-1)/2)*(bw+3)-bw/2;svg+=`<rect x="${x}" y="${h-p.b-bh}" width="${bw}" height="${bh}" rx="3" fill="${colors[j]}"/>`});svg+=`<text class="axis-label" text-anchor="middle" x="${p.l+i*gw+gw/2}" y="${h-9}">${d.label}</text>`});el.innerHTML=svg+'</svg>'}
function renderCharts(){const s=Object.entries(weekly).map(([label,d])=>({label,...d}));bars($('#peopleChart'),s,['planned','present','absent'],['#c9d6e0','#08a3d5','#f47f35']);bars($('#productionChart'),s,['assembly','disassembly'],['#08a3d5','#10b981'])}
function renderProductivity(){const s=Object.entries(weekly).map(([label,d])=>({label,...d}));const el=$('#productivityChart');if(!el)return;const w=850,h=315,p={l:45,r:20,t:20,b:35},min=30,max=48;const point=(v,i)=>[p.l+i*(w-p.l-p.r)/(s.length-1),p.t+(max-v)/(max-min)*(h-p.t-p.b)];let svg=`<svg viewBox="0 0 ${w} ${h}">`;for(let v=30;v<=48;v+=3){let y=point(v,0)[1];svg+=`<line class="grid-line" x1="${p.l}" y1="${y}" x2="${w-p.r}" y2="${y}"/><text class="axis-label" x="8" y="${y+3}">${v}</text>`}let pts=s.map((d,i)=>point(d.productivity,i));svg+=`<line class="line-meta" x1="${p.l}" y1="${point(42,0)[1]}" x2="${w-p.r}" y2="${point(42,0)[1]}"/>`;svg+=`<polyline class="line-prod" points="${pts.map(x=>x.join(',')).join(' ')}"/>`;pts.forEach((pt,i)=>svg+=`<circle class="dot-prod" cx="${pt[0]}" cy="${pt[1]}" r="5"/><text class="axis-label" text-anchor="middle" x="${pt[0]}" y="${h-10}">${s[i].label}</text><text class="axis-label" text-anchor="middle" x="${pt[0]}" y="${pt[1]-11}">${fmt(s[i].productivity)}</text>`);el.innerHTML=svg+'</svg>'}
function renderActivities(filter=''){const q=filter.toLowerCase();$('#activityTable').innerHTML=activities.filter(a=>Object.values(a).join(' ').toLowerCase().includes(q)).map(a=>`<tr><td><strong>${a.id}</strong></td><td><strong>${a.activity}</strong></td><td>${a.local}</td><td>${a.leader}</td><td>${a.shift}</td><td><span class="status ${a.status==='Concluído'?'done':a.status==='Programado'?'planned':'progress'}">${a.status}</span></td></tr>`).join('')}
$('#activitySearch').oninput=e=>renderActivities(e.target.value);$('#weekFilter').onchange=e=>renderKpis(e.target.value);$('#clearFilters').onclick=()=>{$('#weekFilter').value='all';renderKpis()};
function openLogin(){$('#loginError').textContent='';$('#loginDialog').showModal()}$('#openLogin').onclick=openLogin;$('#mobileLogin').onclick=openLogin;
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('user')==='planejamento'&&f.get('password')==='engenharia2026'){$('#loginDialog').close();localStorage.setItem('ed-auth','true');navigate('registros');toast('Acesso liberado no modo demonstração.')}else $('#loginError').textContent='Usuário ou senha inválidos.'});
function getRecords(){return JSON.parse(localStorage.getItem('ed-records')||'[]')}function renderRecords(){const r=getRecords();$('#recordTable').innerHTML=r.length?r.map(x=>`<tr><td>${x.date.split('-').reverse().join('/')}</td><td><strong>${x.leader}</strong></td><td>${x.shift}</td><td>${x.planned}</td><td>${x.absent}</td><td>${fmt(+x.assembly)} ML</td><td>${fmt(+x.disassembly)} ML</td><td><span class="status done">Salvo</span></td></tr>`).join(''):`<tr><td colspan="8" style="text-align:center;padding:35px;color:#789">Nenhum lançamento salvo neste navegador.</td></tr>`}
$('#newRecord').onclick=()=>{if(localStorage.getItem('ed-auth')!=='true')return openLogin();$('#recordForm [name=date]').value=new Date().toISOString().slice(0,10);$('#recordDialog').showModal()};$('#recordForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(+data.absent>+data.planned){return toast('Faltas não podem superar o efetivo planejado.')}const r=getRecords();r.unshift(data);localStorage.setItem('ed-records',JSON.stringify(r));$('#recordDialog').close();e.currentTarget.reset();renderRecords();toast('Registro salvo com sucesso.')});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
$('#exportCsv').onclick=()=>{const rows=[['ID','Atividade','Local','Responsável','Turno','Status'],...activities.map(Object.values)];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='programacao-andaimes-s39.csv';a.click();URL.revokeObjectURL(a.href)};
renderKpis();renderCharts();renderProductivity();renderActivities();renderRecords();
